spring.profiles.active=dev
spring.application.name=ecomarket-backend
server.port=8080

server.servlet.context-path=/

logging.level.org.hibernate.SQL=INFO
logging.level.com.ecomarket=DEBUG

spring.jackson.serialization.write-dates-as-timestamps=false
